<?xml version="1.0" encoding="utf-8"?><Database Name="MyShop" Class="DataClassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LENOVO-PC;Initial Catalog=MyShop;Integrated Security=True" SettingsObjectName="CPL_assignment_3.Properties.Settings" SettingsPropertyName="MyShopConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Brand" Member="Brands">
    <Type Name="Brand">
      <Column Name="brand_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="brand_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Brand_Product" Member="Products" ThisKey="brand_id" OtherKey="brand_id" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="product_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="product_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="category" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="brand_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Brand_Product" Member="Brand" ThisKey="brand_id" OtherKey="brand_id" Type="Brand" IsForeignKey="true" />
    </Type>
  </Table>
</Database>